Update README.rst
ansible-collections/overview pull request #229
Opened 2023-10-23 11:41 UTC by nikcode9

typos.

2023-10-24 06:31 UTC, russoz approved these changes
LGTM

2023-10-24 06:58 UTC, Andersson007 commented on README.rst
> +* `Using Ansible Collections <https://docs.ansible.com/ansible/latest/user_guide/collections_using.html>`_.
```suggestion
* `Using Ansible Collections <https://docs.ansible.com/ansible/latest/user_guide/collections_using.html>`_.
```
Should we make the other lines in this section contain periods as well?

2023-10-25 07:16 UTC, Andersson007 commented
> i think it is better to have periods at end of each line here.

Could you please add them?

2023-10-25 07:20 UTC, gotmax23 commented
Thanks for the contribution, @nikcode9. Can you explain more on your reasoning for this change? I don't think adding periods to these sentence fragments is correct.

2023-10-25 12:21 UTC, Andersson007 commented
> Thanks for the contribution, @nikcode9. Can you explain more on your reasoning for this change? I don't think adding periods to these sentence fragments is correct.

@gotmax23 do you mean all or some of the changed sentences? If some, could you please specify them and why you think it's  incorrect? To me it seems if a statement starts with a capital letter it should end with a period when it ends. I'm not an expert though.

2023-10-25 19:09 UTC, gotmax23 requested changes

2023-10-25 19:09 UTC, gotmax23 commented on README.rst
> +* `Using Ansible Collections <https://docs.ansible.com/ansible/latest/user_guide/collections_using.html>`_.
None of these should have periods at the end.

2023-10-25 19:09 UTC, gotmax23 commented on README.rst
> +* `ansible` had major releases twice a year.
```suggestion
* Single package called `ansible`
* `ansible` had major releases twice a year
```

2023-10-25 19:09 UTC, gotmax23 commented on README.rst
>  * Single repository `ansible/ansible <https://github.com/ansible/ansible>`_.
```suggestion
* Single repository `ansible/ansible <https://github.com/ansible/ansible>`_
```

2023-10-25 19:09 UTC, gotmax23 commented on README.rst
> +  * A tiny subset of modules and plugins to allow for a functioning controller.
```suggestion
  * The core Ansible programs, ``ansible-{playbook,galaxy,doc,test,etc}``
  * Some documentation
  * A tiny subset of modules and plugins to allow for a functioning controller
```

2023-10-25 19:09 UTC, gotmax23 commented on README.rst
> +* New features go into the next major release - ie worst case you need to wait 6 months.
```suggestion
* New features go into the next major release, i.e., in the worst case, you need to wait 6 months.
```

2023-10-25 22:14 UTC, russoz commented on README.rst
> +    * Will have their own repo (GitHub, GitLab, etc) with dedicated backlog, ie no more shared massive issue & PR backlog.
```suggestion
    * Will have their own repo (GitHub, GitLab, etc) with dedicated backlog, i.e. no more shared massive issue & PR backlog.
```

2023-10-26 07:00 UTC, Andersson007 commented
@gotmax23 @russoz thanks!

@nikcode9 could you please take a look and press "Commit suggestion" where you agree and express your concerns where you disagree?

2023-10-26 11:59 UTC, Andersson007 commented
@nikcode9 thanks!

@gotmax23 @russoz please take another look

2023-10-27 12:57 UTC, Andersson007 approved these changes

2023-10-31 02:40 UTC, gotmax23 approved these changes

2023-10-31 02:40 UTC, gotmax23 commented on README.rst
> +* `Using Ansible Collections <https://docs.ansible.com/ansible/latest/user_guide/collections_using.html>`_.
https://github.com/ansible-collections/overview/pull/229/commits/a92311160d7778b034aa3bee9c03734d10e60656

2023-10-31 02:45 UTC, merged

2023-10-31 06:30 UTC, Andersson007 commented
@nikcode9 thanks for the contribution!
@russoz @gotmax23 thanks for reviewing and merging!